### ISSUE TITLE
Introspect thor commands?

### ISSUE THREAD

**Issue by emilebosch** [erikhuda/thor#465]
Hi, is there someway i can introspect available commands from code? I.e read in a Thorfile and then enumerate the commands? And necessary paramters and such?

Thanks much.

**Comment by maxlinc** [comment]
It almost sounds like what you're asking for is `thor list` or `thor help`, but trying that out I see a few limitations. Not sure if this is quite what you were talking about but thought I'd add some notes.

The command `thor list` is the closest to what you're asking for but it doesn't include the necessary parameters.
The `help` command does include the parameters and works for [executables built with thor](https://github.com/erikhuda/thor/wiki/Making-An-Executable), but it seems that running `thor help` in a directory containing a thor file will only show the help for thor's own commands and not the ones in the Thorfile. Interestingly, `thor help <command>` still works.

For example in Thor's own repo:
```
$ thor help
Commands:
  thor help [COMMAND]  # Describe available commands or one specific command
  thor install NAME    # Install an optionally named Thor file into your system commands
  thor installed       # List the installed Thor modules and commands
  thor list [SEARCH]   # List the available thor commands (--substring means .*SEARCH)
  thor uninstall NAME  # Uninstall a named Thor module
  thor update NAME     # Update a Thor file from its original location
  thor version         # Show Thor version
```

```
$ thor help release
Usage:
  thor :release

Create tag v0.19.1 and build and push thor-0.19.1.gem to Rubygems
```

It does show up in `thor list`, but without parameters.
```
$ thor list
default
-------
thor :build    # Build thor-0.19.1.gem into the pkg directory
thor :install  # Build and install thor-0.19.1.gem into system gems
thor :release  # Create tag v0.19.1 and build and push thor-0.19.1.gem to Rubygems
thor :spec     # Run RSpec code examples
```

**Comment by maxlinc** [comment]
Now a slightly off-topic side note: I think it'd be really useful to have something like git's `--porcelain` flag  (to "give the output in an easy-to-parse format for scripts", which will "remain stable across versions regardless of user configuration").

Parsing the list of tasks is useful for:
- Command-line auto-completion
- CI tools that try to automatically find certain tasks like "test", like [travis-build](https://github.com/travis-ci/travis-build).

I've been working on a new tool for the later problem that is similar to travis-build but that acts as a universal frontend for any tasks rather than having a few built-in tasks it supports or assumptions it makes. The idea is that it can aggregate the available tasks from all task runners. So if you have a Thorfile, a Rakefile and a Gruntfile all in the same directory and you run `psychic list tasks` it should be able to show you all of the tasks implemented by thor, rake or grunt. Similarly, if you run something like `psychic run lint` it would find which of those tools have defined a "lint" task defined and either run the first match or run each lint task. So it might use Thor to lint your ruby code and Grunt to lint your javascript code.

An output format that's designed to be simple and machine-readable would useful, especially if it's used by several tools.

**Comment by emilebosch** [comment]
Hi but i was wondering if there was something just readily available. I guess thor on the inside works like:

1 Enumerate the commands
2 Get the command of the user
3 See the params and see if the params of the user are correct
4 If so execute

Therefore i was just looking for somthing like:

```ruby
require 'thor'
Thor = Thor:Load("MyThorFile");
Thor.commands.first.name 
```

etc etc.

However a porcelain would be handy but beating the purpose a bit. But for other usecases would work as autocompelte etc.

**Comment by maxlinc** [comment]
Ah, sorry... I didn't notice you said "from code"

**Comment by RonLek** [comment]
> Now a slightly off-topic side note: I think it'd be really useful to have something like git's `--porcelain` flag (to "give the output in an easy-to-parse format for scripts", which will "remain stable across versions regardless of user configuration").
> 
> Parsing the list of tasks is useful for:
> 
> * Command-line auto-completion
> * CI tools that try to automatically find certain tasks like "test", like [travis-build](https://github.com/travis-ci/travis-build).
> 
> I've been working on a new tool for the latter problem that is similar to travis-build but that acts as a universal frontend for any tasks rather than having a few built-in tasks it supports or assumptions it makes. The idea is that it can aggregate the available tasks from all task runners. So if you have a Thorfile, a Rakefile and a Gruntfile all in the same directory and you run `psychic list tasks` it should be able to show you all of the tasks implemented by thor, rake or grunt. Similarly, if you run something like `psychic run lint` it would find which of those tools have defined a "lint" task defined and either run the first match or run each lint task. So it might use Thor to lint your ruby code and Grunt to lint your javascript code.
> 
> An output format that's designed to be simple and machine-readable would useful, especially if it's used by several tools.

@maxlinc  Could you build the thing above? I'm looking for exactly the same thing in Thor for Command-line autocompletion?
