### ISSUE TITLE
new gem version?

### ISSUE THREAD

**Issue by OutlawAndy** [erikhuda/thor#506]
Is there a timeline for the next gem release?  I would like to take advantage of the fixed regex for numeric option types

**Comment by anbotero** [comment]
@OutlawAndy @sferik I second this.

Just today I was having a boolean `--no-option` and it was duplicating as `--no-no-option` in the usage text, only to find it had been fixed in the code a year ago, but the latest published gem is older than that.

Could you please release a new one? I’ll upload a version of `master` branch to my own Rubygems server, but it’d be nice if I didn’t have to duplicate that effort.

Thanks and keep it up!

**Comment by mbasset** [comment]
👍

**Comment by maxmeyer** [comment]
@mbasset Please prefer to use the UI github introduced - +smiley. You would otherwise spam the gem author with "+1" entries.

**Comment by mbasset** [comment]
@maxmeyer Done. Any news one this?

**Comment by maxmeyer** [comment]
@mbasset Sorry, I just saw the +1. I'm not a maintainer of this particular gem.

**Comment by mbasset** [comment]
@sferik Looks like you have been merging in a number of PR's lately. Would you have any news on a pending release?

**Comment by anbotero** [comment]
Sorry for 👍 , but I don’t see why not make the author receive notifications.

**Comment by mbasset** [comment]
For anyone who sees this. We have a newer version of the gem built under the name `qthor`. Our hope is to only provide this gem until a new version of the main thor is released. It is simply a build of the latest thor code at the date released. https://rubygems.org/gems/qthor

**Comment by anbotero** [comment]
Spamming to bring attention again.

**Comment by rafaelfranca** [comment]
Last time I tried to release it broke bundler and Rails. The new issue that was opened confirm that.

**Comment by OutlawAndy** [comment]
@rafaelfranca That sucks, for sure!
Tends to happen though, when such a heavily depended on gem becomes 2 years out of date.
I feel somewhat responsible, please let me know if you need help with triage
